---
title: Predicting Blood Donations in a Tertiary Care Center Using Time Series Forecasting.
author: ''
date: '2019-04-12'
slug: predicting-blood-donations-in-a-tertiary-care-center-using-time-series-forecasting
categories: []
tags: 
  - article
Status: Published
comments: no
kind: article
link: http://www.ncbi.nlm.nih.gov/pubmed/30942730
citation: '<b>Bischoff F</b>, Koch M do C, Rodrigues PP. <b>Predicting Blood Donations in a Tertiary Care Center Using Time Series Forecasting</b>. <em>Studies in health technology and informatics</em>. 2019;258:135-139.'
doi: 10.3233/978-1-61499-959-1-135
---

The current algorithm to support platelets stock management assumes that there are always sufficient whole blood donations (WBD) to produce the required amount of pooled platelets. Unfortunately, blood donation rate is uncertain so there is the need to backup pooled platelets productions with single-donor (apheresis) collections to compensate periods of low WBD. The aim of this work was to predict the daily number of WBD to a tertiary care center to preemptively account for a decrease of platelets production. We have collected 62,248 blood donations during 3 years, the daily count of which was used to feed (standalone and ensemble versions of) six prediction models, which were evaluated using the Mean Absolute Error (MAE). Forecast models have shown better performances with a MAE of about 8.6 donations, 34% better than using means or medians alone. Trend lines of donations are better modeled by autoregressive integrated moving average (ARIMA) using a frequency of 365 days, the trade-off being the need for at least two years of data.

**Keywords:** blood donations; data mining; forecasting; time series.
