baseurl = "/"
languageCode = "en-us"
title = "Francisco Bischoff"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[social]
    github  = "https://github.com/franzbischoff"
    twitter = "https://twitter.com/franzbischoff"

[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

[[menu.main]]
    name = "Publications"
    url = "/publications/"
    weight = 2

[[menu.main]]
    name = "Software"
    url = "/software/"
    weight = 3

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4

[params]
    author = "Francisco Bischoff"
    description = "Christo nihil præponere."

    # Date format (refer to Go's date format: http://flippinggodateformat.com)
    dateFormat = "2006/12/31"

    # Number of posts to show on main page.
    posts_count = 3

    # Number of publications to show on main page.
    pubs_count = 5

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    #highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "tex"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"
