baseURL: /
title: Francisco Bischoff
author: Francisco Bischoff
copyright: Copyright (c) 2021 Francisco Bischoff
canonifyurls: yes
paginate: 10
theme: franzbischoff
languageCode: en-us
googleAnalytics: G-L8EJYTP892
disqusShortname: franzbischoff
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
  - (^|/)renv$
  - renv\.lock$
enableRobotsTXT: yes
relativeurls: no
pluralizeListTitles: no
buildFuture: yes
sitemap:
  changefreq: weekly
  filename: sitemap.xml
  priority: 0.5
markup:
  goldmark:
    renderer:
      unsafe: yes
permalinks:
  post: /:year/:month/:day/:slug/
social:
  github: https://github.com/franzbischoff
menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Publications
      url: /publications/
      weight: 2
    - name: Software
      url: /software/
      weight: 3
    - name: About
      url: /about/
      weight: 4
params:
  MathJaxCDN: cdnjs.cloudflare.com/ajax/libs/mathjax
  MathJaxIntegrity: sha512-S+79ClJq589gqNbddnVeTBL2CNIaYL3tKs3oPaidENSxukCt0JhPfdvVaoxILiPhdn8Fdw8gjV4fYqy9ldsiSA==
  MathJaxVersion: 3.1.4
  author: Francisco Bischoff
  blogroll:
    - icon: tags
      icon_pack: fa
      link: https://www.r-bloggers.com/
      text: R-Bloggers
    - icon: tags
      icon_pack: fa
      link: https://matrixprofile.org/
      text: Matrix Profile Foundation
  date_format: 2 January 2006
  description: Christo nihil præponere.
  domain: franzbischoff.rbind.io
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
    - tex
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  posts_count: 3
  pubs_count: 5
  seminars_count: 5
  social:
    - icon: university
      icon_pack: fa
      link: http://cintesis.eu/ai4health/
      text: AI4Health Group @ CINTESIS, Rua Dr. Plácido da Costa, s/n 4200-450, Porto, Portugal.
    - icon: envelope
      icon_pack: fa
      link: mailto:fbischoff@med.up.pt
      text: fbischoff@med.up.pt
    - icon: github-alt
      icon_pack: fa
      link: https://github.com/franzbischoff/
      site: GitHub
      text: franzbischoff
    - icon: researchgate
      icon_pack: ai
      link: https://www.researchgate.net/profile/Francisco_Bischoff
      text: ResearchGate
