---
title: tsmp is going big!
author: Francisco Bischoff
date: '2020-08-29'
categories:
  - r-bloggers
  - R
  - tsmp
tags:
  - R
slug: tsmp-package-is-going-big
mathjax: yes
---

Since the beginning of the `tsmp` package, it was evident that a series of algorithms around the Matrix Profile would pop-up sooner or later.

After the creation of the Matrix Profile Foundation [(MPF)](https://matrixprofile.org/), the `tsmp` package had doubled the number of monthly downloads, and that is a good thing!

The current version of `tsmp`, as shown in the [previous post](https://franzbischoff.rbind.io/posts/introducing-the-matrix-profile-api/) had added the new Pan-Matrix Profile and introduced the Matrix Profile API that aims to standardize high-level tools across multiple programming languages.

Now my focus will be on speed and robustness of the package. Currently I can say that the speed improvement is 25% for STAMP and STOMP.

The `tsmp` package will keep the current structure, but the "core" algorithms will be moved to a new dependency package called `matrixprofiler`.

This package will be specialized on low-level (Rcpp) implementation of MASS, STAMP, STOMP, etc. This will let the `tsmp` more flexible implement algorithms that use the Matrix Profile as the base for the application tasks as "motif search", "snippet search", or other algorithms that may appear.

`matrixprofiler` will tend to be less updated and very stable. Those who just want the basics, will get to work with this package alone, but it is safer to install the `tsmp` and have the former as dependency.

Stay tuned for the first release.

[Test](https://patient-cherry-7bc4.franzbischoff.workers.dev)
